### ISSUE TITLE
Add 1-D audio sample support

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#1006]
> from https://github.com/tensorflow/io/pull/803#issuecomment-648037741

can someone please provide me with an example of how to resample a 1 channel audio wave because its not clear how to use this feature

Note input has to be 2-D [samples, channels]. The quality is the quality
its not mentioned anywhere in the docs

if my understanding is correct samples is a 2d tensor with both channels stacked but when follow this logic it does not work

/cc @xnio94

**Comment by yongtang** [comment]
@xnio94 Added PR #1007 to support 1-channel (1D) audio.

**Comment by xnio94** [comment]
i have a 1 channel waveform (taken from tfds.speech_commands ) and i want to resample it using tfio.audio.resample
from 16000hz to 8000hz

i cast the waveform to an int16 tensor
`tf.Tensor([  0  -2  -1 ... -14 -17 -20], shape=(16000,), dtype=int16)`
and i tried `tfio.audio.resample(my_1d_wave, 16000, 8000)`
and also `tfio.audio.resample([my_1d_wave,1], 16000, 8000)`
and many other things, but i still don't get how it supposed to work because in the best case it gave me a tensor filled with zeros, the documentation is not clear and i didn't find any examples how to use it on the internet
if my understanding is correct, it does not matter if the audio is 1 channel or 2 because the resampling is done independently for both channel so I should be able to do something like `resample([audio, audio])[0]` if resample only support 2 channels

**Comment by yongtang** [comment]
@xnio94 The PR  #1007 has been merged and resample support 1-D data now if you install  nightly build through `python3 -m pip install tensorflow-io-nightly`.

We will release a new version next week which will allow you to use the 1-D resample support through `python3 -m pip install tensorflow-io` after that.

**Comment by xnio94** [comment]
Thanks man, i already tried it last time and it looks greats.
