### ISSUE TITLE
setup.py: Dependency on tensorflow

### ISSUE THREAD

**Issue by wookayin** [tensorflow/io#124]
When installing the current version of tensorflow-io (`pip install tensorflow-io-nightly`), it tries to install its dependency package `tensorflow`, not `tensorflow-gpu` if the gpu one is installed. As a result `tensorflow` could be installed mistakenly instead of `tensorflow-gpu`.

I have no idea about specifying conditional dependencies. How about we simply do not require `tensorflow` in REQUIRED_PACKAGE from setup.py?

**Comment by yongtang** [comment]
@wookayin The following could be used:
```
ubuntu@ubuntu:/# pip3 install -q tensorflow-gpu
ubuntu@ubuntu:/# pip3 install -q tensorflow-io-nightly --no-deps
```

For required package in setup.py, we may still need to specify the version, as `tensorflow-io` depends on specific tensorflow (or tensorflow-gpu) version to run correctly (due to C++ api). For example, tensorflow-io 0.3.0 will not work with tensorflow/tensorflow-gpu 1.13.1

Using `--no-deps` may not be ideal for now. Though there is some progress on the tensorflow side to consolidate `tensorflow` and `tensorflow-gpu` package:
https://github.com/tensorflow/tensorflow/pull/24860

Hopefully pretty soon we should be able to only have one package to depend on.

**Comment by psitronic** [comment]
As I understood this issue was not fixed yet. Is it possible in `setup.py` just check if either `tensorflow` of `tenserflow-gpu` was installed?

**Comment by wookayin** [comment]
@psitronic That's correct. However starting from TF 1.15, tensorflow will by default include GPU support with just `tensorflow` pip package. See [this link](https://groups.google.com/a/tensorflow.org/forum/#!topic/developers/iRCt5m4qUz0)

**Comment by psitronic** [comment]
@wookayin Thank you for the reply. However, according to the link you mentioned two packages for cpu and gpu support still will exist and will be used. I wouldn't cancel a possibility to use `tensorflow-io` only with either gpu or cpu packages.

**Comment by kvignesh1420** [comment]
@yongtang I hope this can be closed now?

**Comment by yongtang** [comment]
@kvignesh1420 Yes I think this can be closed.
