### ISSUE TITLE
Support decoding video from byte stream for tensorflow-io

### ISSUE THREAD

**Issue by wookayin** [tensorflow/io#144]
Video (ffmpeg) support (#30) is awesome. I was wondering if we can improve the video dataset API by having a counterpart of [`tf.contrib.ffmpeg.decode_video`](https://www.tensorflow.org/api_docs/python/tf/contrib/ffmpeg/decode_video), which decodes the video from the contents bytestream (`tf.string`) rather than a filename.

This can be useful in some use cases where videos are encoded and stored in a TFRecord dataset. A side note: it seems that a couple of [exemplar video datasets](https://github.com/tensorflow/datasets/blob/master/docs/datasets.md#video) stores a sequence of frame images (encoded as PNG) so I'm not 100% sure if this feature would be worthwhile.

I took a quick look at the C++ kernel implementation but the implementation seems quite tricky. One way is, as in `tf.contrib.ffmpeg.decode_video`, we could write the buffer content into a temporary file but I am doubtful this is the right way. Pipe or reading from stdin could work, but needs some study.

**Comment by yongtang** [comment]
@wookayin The appropriate way to achieve it, I remember, is to set callback `open/read` functions in `AVFormatContext` , so that `avformat_open_input` will use the open/read callback function instead (and bypass filename open).

In case a memory buffer is passed by, the open/read callback will simply copy the buffer around so that FFmpeg could use the copied buffer (than read buffer from file).

**Comment by wookayin** [comment]
Hi @yongtang, thanks for the guidance. I will look into that soon to see if I can implement this functionality.

**Comment by yongtang** [comment]
@wookayin Fantastic! Let me know if you encounter any issues.

**Comment by yongtang** [comment]
@wookayin Added a PR #295 to support reading video from streams.
