### ISSUE TITLE
Ignite tests fail with python 3.4 and 3.6

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#23]
While running tests on Travis CI, it looks like ignite tests  `//tensorflow_io/ignite:ignite_py_test` fail with python 3.4:
https://travis-ci.org/tensorflow/io/jobs/467306695

Python 3.6 tests also fail with `//tensorflow_io/ignite:ignite_py_test`
https://travis-ci.org/tensorflow/io/jobs/467306697

It may worth to take a look.

**Comment by dmitrievanthony** [comment]
Thanks, @yongtang. These tests can run concurrently, I think the root cause is another. Actually, when I start Ignite in Docker container I can't easily understand outside if Ignite is ready or not and I just wait for 5 seconds. Looks like 5 seconds waiting is not the best choice.

Let me think a bit about it, I'll check if it's possible to ensure that Ignite is ready without waiting. Meanwhile, if this fails are frequent I can increase the waiting period.

**Comment by dmitrievanthony** [comment]
BTW, do you know if it's possible to download raw log from our Travis without special characters? Currently I see the raw log like this:

```
travis_fold:start:worker_info
[0K[33;1mWorker information[0m
```

**Comment by yongtang** [comment]
With the PR #37 merged, this issue has been fix, so closing.
