### ISSUE TITLE
AlibabaCloud OSS support

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#41]
This feature request is from  tensorflow/tensorflow#24556 (/cc @oss-developer):

AlibabaCloud Object Storage Service(OSS) is one of the most widely used cloud stroage services in the world. Could I ask for OSS support with tensorflow?

**Comment by terrytangyuan** [comment]
As mentioned in last community call, we have support for this internally and will open source it soon. cc: @wangkuiyi @ywskycn

**Comment by terrytangyuan** [comment]
@yongtang Would you be able to create release branches in the repo so that we could back-port OSS support to TF IO for different TF versions (v1.12 and v1.13). Note that currently TF IO master branch requires `tensorflow>=1.13.0,<1.14.0`. We'd want to support TF v.12 users as well and it would be better if we can avoid maintaining our own fork.

Also cc @zou000 who's porting the OSS Op over to TF IO.

**Comment by yongtang** [comment]
@terrytangyuan I think a feasible solution is to create a branch based on v0.3.0, as v0.3.0 is based on TF 1.12 and fully tested. We could release a v0.3.1 version with OSS support, then cherry-pick the changes to master branch for 1.13.1 support.

**Comment by terrytangyuan** [comment]
That sounds good to me. @zou000 Would this work for you?

**Comment by zou000** [comment]
Yes, this would work for us. Thanks for doing this.

-- Li

**Comment by yongtang** [comment]
@zou000 Added a branch R0.3, you can create a PR to this branch for 1.12 support.
