### ISSUE TITLE
to_dataset() method doesn't exist on IOTensor

### ISSUE THREAD

**Issue by carlthome** [tensorflow/io#580]
First of all, thanks for working on improving I/O in TensorFlow. It will be a crucial and very welcome addition (serializing `tf.Tensor` to bytestrings and squeezing them into `tf.train.Example` protobufs sucks). Especially lazy random access reads would be a killer feature for DL models on audio data (e.g. WAVs hosted on bucket storage).

On the latest PyPI release (0.9.0) I'm trying to use `to_dataset()` and get an `AttributeError`. Is the docstring stale (or premature?): https://github.com/tensorflow/io/blob/v0.9.0/tensorflow_io/core/python/ops/io_tensor.py#L171-L174

# MCVE
```py
import tensorflow_io as tfio

wav = tfio.IOTensor.from_audio("my_audio.wav")
wav.window(1024).to_dataset()
```
>AttributeError: 'BaseIOTensor' object has no attribute 'to_dataset'

**Comment by yongtang** [comment]
@carlthome Thanks for helping raise the issue! At the beginning IOTensor was only for either standalone Tensor with single data type (e.g., Audio), or for columnar Tensors where it consists of a set of Tensor with the same shape (or same dim[0]), but different data types.

However, later it was found out that some of the data input does not conform to the above two scenarios. One example is the HDF5 which for each dataset(in hdf5) any shape could be possible. Another example is TIFF where each individual image frame could have completely different shapes.

For those two scenarios it is not possible to convert to dataset as tf.data requires `dim[0]` to be equal at the minimum.

We are in the process of rework on the API so that only a subset of IOTensor classes is exposed a `to_dataset` (whenever possible). Audio is definitely possible, though.

In case of audio files, if you just need to import the whole audio data into a dataset then you could use `tfio.IODataset.from_audio()` for now.

If you want to combine partial data reading with AudioIOTensor/tf.data, then I will try to see if we could add the method soon.

**Comment by carlthome** [comment]
Great! `tfio.IODataset.from_audio()` is what I was looking for, so this is more of a docstring bug than a feature request.

**Comment by carlthome** [comment]
Closing because this is pretty stale today.
