### ISSUE TITLE
tf.data doesn't work with AudioIOTensor

### ISSUE THREAD

**Issue by carlthome** [tensorflow/io#581]
AFAIK `tf.data` always applies `@tf.function` to everything for performance reasons (e.g. distributed compute). This means that `tfio.IOTensor.from_audio` cannot be used in a `tf.data` pipeline as the constructor calls `.numpy()`. Am I misunderstanding how `tfio.IOTensor` is intended to be used or is this a bug?

# MCVE
```py
import tensorflow_io as tfio


def load(path):
    wav = tfio.IOTensor.from_audio(path)
    offset = int(1.0 * wav.rate)
    duration = int(3.0 * wav.rate)
    return wav[start:start + offset].to_tensor()


tf.data.Dataset.from_tensor_slices(["my_audio.wav"]).map(load)
```

```
AttributeError: in converted code:

    <ipython-input-87-7e40b48025cf>:5 load  *
        wav = tfio.IOTensor.from_audio(path)
    /usr/local/lib/python3.6/dist-packages/tensorflow_io/core/python/ops/io_tensor.py:243 from_audio  *
        return audio_io_tensor_ops.AudioIOTensor(filename, internal=True) # pylint: disable=protected-access
    /usr/local/lib/python3.6/dist-packages/tensorflow_io/core/python/ops/audio_io_tensor_ops.py:68 __init__
        shape = tf.TensorShape(shape.numpy())

AttributeError: 'Tensor' object has no attribute 'numpy'
```

**Comment by faroit** [comment]
this was exactly the same problem I came up in my first tf.io tests here. @yongtang could you help us?

**Comment by yongtang** [comment]
@carlthome @faroit thanks for helping raise the issue here!

To explain some background. The tf.data pipeline, and tf.function creates subgraph in tensorflow and executes in graph mode. (Even if you invoke in 2.0 and eager mode enabled). The advantage is to have an efficient data pipeline without switch back and forth python binding.

In other words, all the functions passed in `tf.data.Dataset.map` has to be executable in graph mode, or has been converted by autograph to be executable in graph mode.

In tensorflow-io, one of the priority is to adds convenient functions/methods so that users could use TensorFlow directly to process data input.

To elaborate further, in the past,  a lot of information has to be pre-known for tf.data in order to build a true data pipeline (since tf.data is always in graph mode). One of the issues I encountered was in the past to try to feed a CSV file to tf.data. At the minimum I have to specify a list of data types and record_defaults mandatory:
```
CsvDataset(filenames, record_defaults,...)
```

That means for a csv file with 20 columns (very common in real production env), I have to specify 20 data types.

That promotes the idea of "parsing the metadata" automatically in eager mode, then do a further processing in graph mode (to have an efficient pipeline).

In `IOTensor`'s case, as you could see, all of the classes does not requires any user knobs. It will parse the meta data information in eager mode, then give you the ability to lazily read data in graph mode.

For that reason, it may not be the best fit to pass into IOTensor directly in tf.data. It still might be possible, if the "meta data parsing" could be done entirely in graph mode. That means convert while loop into `tf.while`, convert select statement into `tf.where`, etc. That might take some additional time.

On the other hand, depending on your usage, there might be some alternative path that could achieve what you intend to do.

@carlthome I took a look at your example, I think there might be two possibilities:

1) If you are looking for parsing one file, then you could just:
   ```
   audio = load("my_audio.wav")
   tf.data.Dataset.from_tensor_slices(audio)
   ```
   I think that will just give you the result.

2) If you are looking for parsing a set of files and always extract the [offset:offset+length] of **EVERY** file, then it might be need some additional work. I might be able to add a couple of methods to make this happen.

**Comment by MarkDaoust** [comment]
Isn't this use-case also covered by `tfio.IODataset.from_audio(path)` which is a convienient way to load a wav as a dataset.

**Comment by dzubo** [comment]
> If you are looking for parsing a set of files and always extract the [offset:offset+length] of EVERY file, 

that would be awesome to have something like this. I see that ` _AudioIODatasetFunction.__call__()` already has `start` and `stop` parameters, but we can't use them in Keras/Tensorflow code, right?

**Comment by yongtang** [comment]
The initial idea was that IOTensor will read and parse the meta data of an input (e.g., audio file), and use meta data automatically without user knobs. For example, For AudioIOTensor, you don't need to know anything about the audio file before hand.

In order to wire up AudioIOTensor, all necessarily information, e.g., data type of uint8/16/32, shape, etc will need to be done in graph run time. It is a little challenging as graph requires at least data type of the output to be known before hand.

Having said that, I think it might be possible to use `tf.switch_case` to wire up the graph to achieve runtime graph parameterization. Let me take a look and see if I can come up with something quick.

**Comment by yongtang** [comment]
Ah its still not possible as `tf.switch_case` requires the same data type across multiple branches.

In that situation, I think the viable solution would be to ask user to provide the data type (before graph runs) if the function is to be run with tf.data.Dataset.

**Comment by hollowgalaxy** [comment]
I got same error when I tried to use from `tensorflow_io.ffmpeg.VideoDataset` in a function with a `@tf.function` decorator.

**Comment by yongtang** [comment]
@hollowgalaxy the Video Dataset might a different scenario. As you may know, all dataset are constructing a subgraph and all the `dataset.map()` always runs in graph mode. At the same time, tf.function is also constructing a subgraph. So combining tf.function with tf.data will not speed up. (tf.data.map actually did the autograph implicitly already).

Can you explain a little further about what you intend to do?

Wondering if you are looking for a C++ kernel ops like `decode_video` instead, so that you could use it in things like `tf.data.Dataset.map(lambda x: decode_video(x....))`?

**Comment by yongtang** [comment]
@hollowgalaxy If you are looking for `decode_video` types of ops to wire up the dataset then it is available: https://github.com/tensorflow/io/blob/3f9e8708ad8c22d1161b61f96c39cff1304e5156/tensorflow_io/core/python/experimental/ffmpeg_ops.py#L21

**Comment by hollowgalaxy** [comment]
I was using the map function from a CSV dataset to create videos and labels. The tf.function was used to because some conditionals were being done and I wanted those conditionals to be part of the graph. It also has some stuff that processes the video such as (`skip` and `take` as example given those conditionals). 

Looks like `decode_video` can do the job however, not sure what the index value is supposed to be. Since I'm using 0.9, found function in `tensorflow_io.ffmpeg.python.ops.ffmpeg_ops.decode_video`

Also how would decode video work for really long videos? Is it going to partially load in the video? or am I misunderstanding VideoDataset? (I thought it was loading only a part of the video, until the frames needed are reached).

**Comment by faroit** [comment]
@yongtang reading your suggestions I feel that most users would probably like a `decode_audio` op that they can integrate in their `tf.data` pipeline. Is that possible?

**Comment by yongtang** [comment]
Added PR ##615 to solve the `using IOTensor inside another tf.data.Dataset` or `using IODataset (a subclass of Dataset) inside another tf.data.Dataset` issue.

**Comment by yongtang** [comment]
To explain a little about what was happening and why it could be challenging:
1) Initially tf.data was designed as a pipeline in graph mode with efficiency as the goal. The usage of tf.data.Dataset in eager mode was outside of the initial goal.
   Later on `for d in dataset` types of iteration was added but that is more of a complement.
2) It was not possible to random access with tf.data as tf.data always iterate from beginning to end.
3) It was not possible to get meta data as graph mode essentially is a one-shot graph operation and all of the information about shape and dtype has to be defined exactly before hand.

To give an example about why item 2) mentioned above could be an issue: as many in this issue thread have noticed, if you have a big audio file with GB's of data, you have to read all the way from the beginning to end even if you only need to take, say the very last 5 min of the data.

To give an example about why item 3) mentioned above could be an issue: if you have an audio file of wav and you don't know what is inside, you will not able to find out the true data type. Is the WAV file 16 bit or 24 bit? Unless you have another program open and check the metadata, you will not be able to know it. And without dtype, you have to either `try and see`, or `always promote to 32bit/etc`.

Some of the goals of tensorflow/io were to address 2) and 3).

In order to address 2), we introduced C++ kernel ops that allows you to read based on a [start:stop] chunk of the data, thus that forms the initial idea about IOTensor.

In order to address 3), we utilize eager mode to obtain the metadata in one run, then run the graph in another run. This essentially eliminate the need for user to provide any information other than data type. This is also part of IOTensor.

However, as we introduce the eager mode (need first run to get dtype, then second run to construct the graph), it is not possible to run IOTensor in graph mode any more.

Now with PR #615, we separated two scenarios:
1) User provides the data type before hand. In that situation, we could infer everything else and construct the graph in one pass. Thus it is possible to run "AudioGraphIOTensor" in graph mode.
2) User does not know anything about what is inside a file other than "it is a WAV file of any bits". In that case, user still could use the "AudioIOTensor" in eager mode to get everything. The down side is that the `AudioIOTensor` is not possible to run in graph mode (thus not embedded in tf.data.Dataset pipeline).

IODataset/GraphIODataset is in similar situation.

If user provides data type, then we could construct the graph without actually run, thus GraphIODataset could be feed into tf.data.Dataset (note this is like Dataset inside outer Dataset).

If user does not have any information about the data type, then data type has to be probed in one run first, to construct the IODataset. This IODataset will not be able to run inside another tf.data.Dataset.

Here is the usage of example of enabling "graph mode for IOTensor", and "graph mode for IODataset":
```python
import tensorflow_io as tfio

# create Graph mode IOTensor, could be run inside tf.data
# but tf.int32 is necessary and could not be avoided.
tfio.IOTensor.graph(tf.int32).from_audio(filename) 

# create eager mode IOTensor, could not run inside tf.data
tfio.IOTensor.from_audio(filename) 

# create Graph mode IODataset, could be run inside tf.data
# but user has to indicate the output data type of tf.int32
tfio.IODataset.graph(tf.int32).from_audio(filename) 

# create eager mode IODataset, not need for tf.int32 input
# but could not run inside tf.data
tfio.IODataset.from_audio(filename) 
```

Below is the example of running GraphIOTensor inside tf.data.Dataset's map:
```python

import tensorflow as tf
import tensorflow_io as tfio

filename_dataset = tf.data.Dataset.from_tensor_slices(
    [audio_path, audio_path])
position_dataset = tf.data.Dataset.from_tensor_slices(
    [tf.constant(1000, tf.int64), tf.constant(2000, tf.int64)])

dataset = tf.data.Dataset.zip((filename_dataset, position_dataset))

# Note: @tf.function is actually not needed, as tf.data.Dataset
# will automatically wrap the `func` into a graph anyway.
# The following is purely for explanation purposes.
# Return: audio chunk from position:position+100, and the rate.
@tf.function
def func(filename, position):
  audio = tfio.IOTensor.graph(tf.int16).from_audio(filename)
  return audio[position:position+100], audio.rate

dataset = dataset.map(func)

for (data, rate) in dataset:
  print(data, rate)
```


Below is the example of running GraphIODataset inside tf.data.Dataset's map, essentially a "dataset inside another dataset graph":

```python
import tensorflow as tf
import tensorflow_io as tfio

filename_dataset = tf.data.Dataset.from_tensor_slices(
    [audio_path, audio_path])
position_dataset = tf.data.Dataset.from_tensor_slices(
    [tf.constant(1000, tf.int64), tf.constant(2000, tf.int64)])

dataset = tf.data.Dataset.zip((filename_dataset, position_dataset))

# Note: @tf.function is actually not needed, as tf.data.Dataset
# will automatically wrap the `func` into a graph anyway.
# The following is purely for explanation purposes.
# Return: an embedded dataset (in an outer dataset) for position:position+100
@tf.function
def func(filename, position):
  audio_dataset = tfio.IODataset.graph(tf.int16).from_audio(filename)
  return audio_dataset.skip(position).take(100)

dataset = dataset.map(func)

# Notice audio_dataset in dataset:
for audio_dataset in dataset:
  for value in audio_dataset:
    print(value)
```

**Comment by yongtang** [comment]
@hollowgalaxy the index is the video stream index within the video container (e.g., mp4), as you may have multiple sub streams.

For your need the decode_video may not work if the video is long. I will take a look and overt the IOTensor or IODataset into graph mode so that it could be used with your CSVDataset.

**Comment by hollowgalaxy** [comment]
@yongtang  thank you for the hard work. moving this to a new issue to avoid hijacking.https://github.com/tensorflow/io/issues/616
