### ISSUE TITLE
Support ogg file format

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#650]
This issue is opened to track the progress for ogg audio format.

In tensorflow-io, we have the support for various audio format for FFmpeg. However, FFmpeg lacks fine control of the seek ability.

The plan is to support a small widely used audio format in `IOTensor.from_audio` natively (not through FFmpeg). And FFmpeg will only be a fallback method for user to use (without fine control of seek).

At the moment WAV file is supported, through we can certainly support ogg in `from_audio`. We could even detect format internally.

So the usage would be that user can feed wav or ogg into `from_audio` without any modification of the code. .

/cc @faroit

**Comment by faroit** [comment]
> The plan is to support a small widely used audio format in IOTensor.from_audio natively (not through FFmpeg). And FFmpeg will only be a fallback method for user to use (without fine control of seek).

that sounds like a good plan but I am not sure if such an achievement would be a requirement for most users. My guess is that many users would be fine with coarse seeking so that they could do random chunked training of long files. In any case, the most widely used format is mp3 which does not support exact seeking. 

I think I would prefer to focus on 

* making from_ffmpeg as efficient and convenient as possible,
* allow ffmpeg decoding to be used used from `GraphIOTensor` or otherwise be interfaced from `tf.data`
* seeking could stay inaccurate in seconds instead of samples

Should I open another issue for this?

**Comment by yongtang** [comment]
> Should I open another issue for this

@faroit sounds good to me. Can you open an issue for it?
