### ISSUE TITLE
Support for tensorflow 2.1.0

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/io#658]
Do you know when you will be able to support `tensorflow` 2.1.0?

Right now when I install `tfio-nightly` with no dependencies with `tensorflow` 2.1.0, when do `import tensorflow_io as tfio`, `tfio` is an empty module (i.e. `dir(tfio)` doesn't contain `IOTensor` etc...).

I can write a reproducible example if needed.

**Comment by yongtang** [comment]
@zaccharieramzi sorry for the late reply. It is approaching to year end so a little slowed.

At the moment the plan is to get at least #649 in so that macOS and linux should have similar performance (with SSE4.2 and AVX). Then we will cut a release still based on TF 2.0.

I hope we will get the new release 0.10.0 in a couple of days.

Once a new release is out, we will switch to 2.1.0rc0 in nightly build, and release another version 0.11.0 (for TF2.1) when TF2.1 final is out.

**Comment by yongtang** [comment]
PR #659 bumps TF to 2.1.0rc+
