### ISSUE TITLE
libtensorflow_io.so not found from repo directory

### ISSUE THREAD

**Issue by marioecd** [tensorflow/io#914]
I cloned the tensorflow-io repo into my VM. Then I built it and tested it successfully.
$ bazel build -s --verbose_failures //tensorflow_io/...
$ TFIO_DATAPATH=bazel-bin python3 -m pytest -s -v tests/test_serialization_eager.py

I then go into io, create a python script with the code from the readme "https://github.com/tensorflow/io"
import tensorflow as tf
import tensorflow_io as tfio
.. etc

When I run the python script I get an error about libtensorflow_io.so

$ cd io
$ python myscript.py

/home/marioecd/io/tensorflow_io/core/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory'

Can someone detect if I am doing something wrong here? My goal is to download tensorflow-io from git, then build it, then run a python script where I load the tensorflow-io I've built and run some sample commands.

**Comment by yongtang** [comment]
@marioecd If you want to run anything without packing a wheel and install, then you will need to pass `TFIO_DATAPATH=bazel-bin ` in environmental variable so that the shared object is exposed.

You may notice the `libtensorflow_io.so` is located in `bazel-bin/tensorflow_io/core/python/ops/libtensorflow_io.so`, not the normal `tensorflow_io/core/python/ops/libtensorflow_io.so`.


Also notice that is the reason why the following:
```
$ TFIO_DATAPATH=bazel-bin python3 -m pytest -s -v tests/test_serialization_eager.py
```

**Comment by marioecd** [comment]
Yep. That's what I was doing wrong. Thanks! It works now.
