### ISSUE TITLE
lint check failing "./tensorflow_io/core/BUILD # reformat" on PR

### ISSUE THREAD

**Issue by marioecd** [tensorflow/io#920]
I have a pull request for the nightly branch that's failing the lint check.
I think the lint output doesn't really show what the problem is. The output at the end shows is basically:

./tensorflow_io/core/BUILD # reformat
##[error]Process completed with exit code 4.

The PR request check run is:
https://github.com/tensorflow/io/pull/919/checks?check_run_id=616575403

**Comment by yongtang** [comment]
@marioecd The following command:
```
bazel run //tools/lint:lint -- bazel
```

Will automatically reformat all bazel files (`WORKSPACE`, `BUILD`, and `.bzl`) with bazel `buildifier`.

You can add the changes and push to PR.

Once the files are reformatted, then the following command for lint checking will pass. It is also the command line run by GitHub CI.
```
bazel run //tools/lint:check -- bazel
```


Because Bazel's `buildifier` does not really have a `--check` option, we emulate the `check` option by using `buildifier` to sanitize the files, and compare with the new file and old file to see if they differs. So the output might be a little confusing.

**Comment by marioecd** [comment]
oh thanks!
