### ISSUE TITLE
cc_test with dependency on tensorflow?

### ISSUE THREAD

**Issue by marioecd** [tensorflow/io#924]
Has anyone run any TFIO cc_test with a dependency on tensorflow? I am trying to add in a cc_test for a new component. The new component has a depedency on tensorflow  "@local_config_tf//:libtensorflow_framework", but when I run its bazel test I get error:

**error while loading shared libraries: libtensorflow_framework.so.2: cannot open shared object file: No such file or directory.**

When running python I can add TFIO_DATAPATH=bazel-bin to find the shared libraries in the python environment; but I don't know if something similar can be done to run bazel test for a cc_test target.

Is this something that should be possible?

**Comment by yongtang** [comment]
@marioecd Will it be possible to write in python? Due to the lib dependency it might not be very straightforward to get the `cc_test` working in `bazel`, as ` libtensorflow_framework.so.2` is installed from environment. This is different from tensorflow repo where the `libtensorflow_framework.so.2` is built from source and is already visible from bazel. (It could be possible, though, likely with `genrule` or `data` field of the bazel).

If the test is in python then it will be easier to get around the limitation of bazel.

**Comment by marioecd** [comment]
Hmm, these would be unit tests for a cc_library component. I think python test are out of the question for these to unit test this component. The only question is whether I can extract away enough TF stuff from it and try to test the non-TF parts with cc_test. But some parts of it are going to be very hard to unit test with python. Thanks for the context!
