### ISSUE TITLE
HDF5IODataset boolean mask returning always false produces index error.

### ISSUE THREAD

**Issue by ramonemiliani93** [tensorflow/io#968]
While creating and HDF5 dataset using `tfio.IODataset.from_hdf5` I get: 

`tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 0 of dimension 0 out of bounds.`

This seems to be caused by line 32 in hdf5_dataset_ops.py:

`shape = tf.boolean_mask(shapes, tf.math.equal(components, dataset))[0]`

where the component is a tensor string type with a forward slash and dataset is a string.

I am using the nightly build.

**Comment by ramonemiliani93** [comment]
Update:
 passing ` tf.convert_to_tensor("/" + dataset)` as the dataset makes everything work.

**Comment by yongtang** [comment]
Thanks for the report @ramonemiliani93. As you might notice a '/' is needed for specify dataset. The reason is that dataset could have a path that span into multiple nodes e..g, `/node1/node2/dataset` so '/' is needed to figure out the dataset referring to. I will close the issue as it seems this is resolved, but feel free to reopen if you have any questions.
