### ISSUE TITLE
bazel windows setup-python fails

### ISSUE THREAD

**Issue by marioecd** [tensorflow/io#971]
I think there may be a miss-configuration causing bazel windows check to fail like:

 Run actions/setup-python@v10s
    BAZEL_OPTIMIZATION: --copt=-msse4.2 --copt=-mavx --compilation_mode=opt
Run actions/setup-python@v1
  with:
    python-version: 3.7.6
    architecture: x64
  env:
    BAZEL_VERSION: 3.0.0
    BAZEL_OPTIMIZATION: --copt=-msse4.2 --copt=-mavx --compilation_mode=opt
**##[error]Version 3.7.6 with arch x64 not found**
Available versions:
2.7.18 (x86)
3.5.4 (x86)
3.6.8 (x86)
3.7.7 (x86)
3.8.2 (x86)
2.7.18 (x64)
3.5.4 (x64)
3.6.8 (x64)
3.7.7 (x64)
3.8.2 (x64)

**Comment by yongtang** [comment]
@marioecd This issue was fixed in master branch  (in PR #954) but since nightly branch was falling behind, the error showed up again.

I will rebase the nightly branch to carry those changes. Though after my nightly rebase you may need to resubmit your local branch as well. Let me rebase the nightly first.

**Comment by marioecd** [comment]
Oh ok. Will do. Thanks!
