### ISSUE TITLE
decode_mp3 doesn't return sample rate?

### ISSUE THREAD

**Issue by leoffx** [tensorflow/io#982]
How do I get info about the file sample rate? tf.audio.decode_wav returns it, and it's an important information when you're dealing with recordings sampled from different sources. 

Adding this info, or the automatic resampling as librosa.core.load have, would be interesting, as the current tfio.audio.resample also requires the input rate which you know nothing about.

**Comment by yongtang** [comment]
@leoffx You can use AudioIOTensor to get the `rate` and `shape` metadata:
```
>>> import tensorflow_io as tfio
>>> audio = tfio.audio.AudioIOTensor('file_example_MP3_700KB.mp3')
>>> audio.shape
<tf.Tensor: shape=(2,), dtype=int64, numpy=array([870191,      2])>
>>> audio.rate
<tf.Tensor: shape=(), dtype=int32, numpy=32000>
```

Alternatively, I am working on having a standalone alone ops in #847 to get all possible audio rated  metadata. Though I still need to find out a good way to represent the output info in both graph and eager mode.

I will close this issue for now, since `tfio.audio.AudioIOTensor().rate` provides the needed API. Feel free to reopen if you have further questions, though.

**Comment by douglas125** [comment]
Sorry to reopen this, but how would it be possible to get the rate information if the file is being read as a stream or from a GZIP or TAR without explicitly extracting the mp3?

**Comment by yongtang** [comment]
@douglas125 Get the rate information from a stream head (peek) is not supported at the moment. Since the original issue was to read rate information from a file, Can you open a separate issue to track the feature of stream support?
